[colors]

[colors.bright]
black = "#555555"
blue = "#00a5ff"
cyan = "#74fcf3"
green = "#b8e36d"
magenta = "#ab7aef"
red = "#ff4250"
white = "#fffefe"
yellow = "#ffd852"

[colors.cursor]
cursor = "#f0f000"
text = "#1b1918"

[colors.normal]
black = "#2e2e2e"
blue = "#1877dd"
cyan = "#00ddef"
green = "#9ae204"
magenta = "#805bb5"
red = "#ff260d"
white = "#fffefe"
yellow = "#ffc400"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"
